### ISSUE TITLE
math.prod requires Python >= 3.8

### ISSUE THREAD

**Issue by hypostulate** [sshen8/peglit#1]
The setup.py file asks for Python >= 3.6, but imports require >= 3.8.

[Import statement](https://github.com/sshen8/peglit/blob/public/peglit/utils.py#L4)

[Python documentation for math](https://docs.python.org/3/library/math.html)

> math.prod(iterable, *, start=1)
> Calculate the product of all the elements in the input iterable. The default start value for the product is 1.
> 
> When the iterable is empty, return the start value. This function is intended specifically for use with numeric values and may reject non-numeric types.
> New in version 3.8.

**Comment by sshen8** [comment]
Thanks, I'll make it use numpy.prod instead of math.prod since numpy is already imported
