### ISSUE TITLE
output include another line said  '+ Significant motif:pegRNA interaction predicted'

### ISSUE THREAD

**Issue by Yung-Chien** [sshen8/peglit#2]
Hi @sshen8 ,
After calculating the linker sequences, I found the several output lines include a tag said '+ Significant motif:pegRNA interaction predicted' like below,

![image](https://user-images.githubusercontent.com/44871713/221493179-2b34f818-148d-4c93-af7b-9e17b0ff7145.png)

so how could I chose the output linker sequence, which one is better? 

Thanks in advances,
Yung-Chien

**Comment by sshen8** [comment]
Hi @Yung-Chien, thanks for your question! This warning comes up when the motif sequence is predicted to base pair with something in the epegRNA. Intuitively, this could cause trouble by disrupting the structure of the 3' motif, though we didn't explicitly test this hypothesis.

The warning gets printed _after_ the associated linker sequence, so you could just pick a linker that avoids this predicted interaction (i.e. the 1st, 3rd, or 5th in your screenshot). You could also evaluate the predicted epegRNA folds by running `peglit.inspect <seq_spacer>,<seq_scaffold>,<seq_template>,<seq_pbs>,<seq_motif> <seq_linker>` and manually decide whether it's just a false positive

**Comment by sshen8** [comment]
Hi, I've clarified this warning (see a4ad0ee63561ce3866fa9863352884df6f8cbcc2). Hope that helps, and feel free to ping again if you have any other feedback/questions
