### ISSUE TITLE
CLI gets stuck on step 5/250

### ISSUE THREAD

**Issue by JAMKuttan** [sshen8/peglit#3]
I pulled some of the test data and ran this command...
peglit GGCCCAGACTGAGCACGTGA,GTTTTAGAGCTAGAAATAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGAAAAAGTGGCACCGAGTCGGTGC,TGGAGGAAGCAGGGCTTCCTTTCCTCTGCCATCACTTATCGTCGTCATCCTTGTAATC,CGTGCTCAGTCTG,CGCGGTTCTATCTAGTTACGCGTTAAACCAACTAGAA --linker-pattern NN

My commandline runs this output then just stalls here for a long time.
pegRNA:   0%|                                                         | 0/1 [00:00<?, ?it/s]
Repeats:   0%|                                                       | 0/10 [00:00<?, ?it/s]
Steps:   5%|██▎                                            | 12/250 [00:20<00:09, 25.32it/s]

**Comment by sshen8** [comment]
Hi, I just fixed this in 5173e26498eb9f55cf7dec256bf9d5e016de9281.

Your specified sequence space was quite small, so by step 12, no _new_ candidate sequences could be found. I've fixed the logic to return once the whole search space has been seen. Thanks for pointing this out!

**Comment by JAMKuttan** [comment]
Thansk for the quick update! Can confirm it runs well now
