### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by JAMKuttan** [sshen8/peglit#4]
I have a lit of inputs I am running in batch mode. For all but one I run into this error below. Any ideas of how to resolve?

                                              [A[ATraceback (most recent call last):
  File "/usr/local/bin/peglit", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peglit/peglit.py", line 164, in main
    linker_output, filter_stats, score_cutoff = make_output(args, seq_spacer, seq_scaffold,
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peglit/peglit.py", line 46, in make_output
    linker_output, linker_feats, linker_heap_scores, linker_heap, filter_stats = pegLIT(
                                                                                 ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peglit/peglit.py", line 33, in pegLIT
    linker_output, linker_feats = apply_bottleneck(linker_heap_scores, linker_heap,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peglit/bottleneck.py", line 35, in apply_bottleneck
    return [_pick_best(heap_scores, heap)], features
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peglit/bottleneck.py", line 23, in _pick_best
    idx_chosen = random.choice(idx_maxed)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/random.py", line 369, in choice
    if not seq:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by sshen8** [comment]
Hi, could you please provide an example of what your input looks like? And the exact command you're running?

**Comment by JAMKuttan** [comment]
I apologize for the delay in response Here is my input file. If I run them individually in my script I still get the same issue. 
[pegLit_input_batch.csv](https://github.com/user-attachments/files/16899422/pegLit_input_batch.csv)

**Comment by sshen8** [comment]
Thanks for the file, I was actually able to run `peglit --batch pegLit_input_batch.csv` without any errors (btw here's [the output](https://github.com/user-attachments/files/16900286/pegLit_input_batch_linker_designs.csv)). I wonder if there's some difference in our installations... could you post the output of running `conda list`? Or maybe could you try re-installing pegLIT fresh or in a new environment?

**Comment by JAMKuttan** [comment]
WOW! found the issue. I did a conda list and got the following error.
```
Traceback (most recent call last):
  File "/usr/local/bin/conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```

 So I put peglit into a docker container and run it that way. Very simple dockerfile
```
FROM conda/miniconda3:latest

# Install pegLIT
RUN conda config --add channels defaults; \
    conda config --add channels bioconda; \
    conda config --add channels conda-forge; \
    conda config --set channel_priority strict; \
    conda install parallel peglit procps-ng -y
```
When i run the conda install, it is attempting to overwrite the version of python.

The issue was from the base container. the conda/miniconda3 is an outdated container and I switched to 
continuumio/miniconda3

This seems to have solved all the problems. Thank you for taking the time to look into this. I apologize for the false alarm

**Comment by sshen8** [comment]
Cool glad you figured it out, and thanks for sharing your solution!
